version: '3'

services:
  consul-agent:
    image: consul:1.9.1
    restart: unless-stopped
    environment:
      - CONSUL_BIND_INTERFACE=eth0
      - TZ=Asia/Shanghai
    volumes:
      - $PWD/consul/config:/consul/config
      - $PWD/consul/data:/consul/data
    ports:
      - 8500:8500
    command: ['agent','-server','-bootstrap-expect=1','-node=node1', '-client', '0.0.0.0', '-ui']
    networks:
      - consul-center

networks:
  consul-center: